// Generated by CoffeeScript 1.10.0
(function() {
  var db;

  db = require('./db')(__dirname + "/../db/metrics");

  module.exports = {

    /*
    `get()`
    ------
    Returns some hard coded metrics
     */
    get: function() {
      var key, rs, value;
      rs = db.createReadStream();
      key = '';
      value = '';
      rs.on('data', function(chunk) {
        key += chunk.key;
        return value += chunk.value;
      });
      rs.on('error', function(err) {
        if (err) {
          throw err;
        }
      });
      rs.on('end', function() {
        return console.log(key + " : " + value);
      });
      return [
        {
          key: "" + key,
          value: "" + value
        }
      ];

      /*
      return [
      
        timestamp: new Date('2015-12-01 10:30 UTC').getTime(),
        value: 26
      ,
        timestamp: new Date('2015-12-01 10:35 UTC').getTime(),
        value: 23
      ,
        timestamp: new Date('2015-12-01 10:40 UTC').getTime(),
        value: 20
      ,
        timestamp: new Date('2015-12-01 10:45 UTC').getTime(),
        value: 19
      ,
        timestamp: new Date('2015-12-01 10:50 UTC').getTime(),
        value: 18
      ,
        timestamp: new Date('2015-12-01 10:55 UTC').getTime(),
        value: 20
      ]
       */
    },

    /*
    `save(id, metrics, cb)`
    ------------------------
    Save some metrics with a given id
    Parameters:
    `id`: An integer defining a batch of metrics
    `metrics`: An array of objects with a timestamp and a value
    `callback`: Callback function takes an error or null as parameter
     */
    save: function(id, metrics, callback) {
      var i, len, m, timestamp, value, ws;
      ws = db.createWriteStream();
      ws.on('error', callback);
      ws.on('close', callback);
      for (i = 0, len = metrics.length; i < len; i++) {
        m = metrics[i];
        timestamp = m.timestamp, value = m.value;
        ws.write({
          key: "metric:" + id + ":" + timestamp,
          value: value
        });
      }
      return ws.end();
    }
  };

}).call(this);
