// Generated by CoffeeScript 1.10.0
(function() {
  var db;

  db = require('./db')(__dirname + "/../db/metrics_users");

  module.exports = {

    /*
    `  get()`
    ------
    Returns some hard coded metrics
     */
    get: function(username, callback) {
      var i, metrics_users, rs;
      metrics_users = [];
      i = 0;
      rs = db.createReadStream();
      rs.on('data', function(data) {
        var _, _id_metric, _username, ref;
        ref = data.key.split(':'), _ = ref[0], _username = ref[1], _id_metric = ref[2];
        if (_username === username) {
          metrics_users[i] = {
            username: _username,
            id_metric: _id_metric,
            value: data.value
          };
          return i++;
        }
      });
      rs.on('error', callback);
      return rs.on('close', function() {
        return callback(null, metrics_users);
      });
    },

    /*
    `save(username, id_metric)`
    ------------------------
    Save some metrics with a given username
    Parameters:
    `username`
    `id_metric`
    `callback`: Callback function takes an error or null as parameter
     */
    save: function(username, id_metric, callback) {
      var ws;
      ws = db.createWriteStream();
      ws.on('error', callback);
      ws.on('close', callback);
      ws.write({
        key: "metrics_users:" + username + ":" + id_metric,
        value: ""
      });
      return ws.end();
    }
  };

}).call(this);
