// Generated by CoffeeScript 1.10.0
(function() {
  var db;

  db = require('./db')(__dirname + "/../db/users");

  module.exports = {

    /*
    `get()`
    ------
    Returns some hard coded metrics
     */
    get: function(username, callback) {
      var rs, user;
      user = {};
      rs = db.createReadStream({
        gte: "user:" + username,
        lte: "user:" + username
      });
      rs.on('data', function(data) {
        var _, _email, _name, _password, _username, ref, ref1;
        ref = data.key.split(':'), _ = ref[0], _username = ref[1];
        ref1 = data.value.split('.'), _name = ref1[0], _password = ref1[1], _email = ref1[2];
        return user = {
          username: _username,
          name: _name,
          password: _password,
          email: _email
        };
      });
      rs.on('error', callback);
      return rs.on('close', function() {
        return callback(null, user);
      });
    },
    save: function(username, password, name, email, callback) {
      var ws;
      ws = db.createWriteStream();
      ws.on('error', callback);
      ws.on('close', callback);
      ws.write({
        key: "user:" + username,
        value: name + "." + password + "." + email
      });
      return ws.end();
    }
  };

}).call(this);
