// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {

    /*
    `get()`
    ------
    Returns some hard coded metrics
     */
    get: function() {
      return [
        {
          user: "root",
          password: "root"
        }, {
          user: "phil",
          password: "root"
        }
      ];
    },
    login: function(login, password) {
      var i, j, len, tab, users;
      tab = this.get();
      i = 0;
      for (j = 0, len = tab.length; j < len; j++) {
        users = tab[j];
        if (login === ("" + users.user) && password === ("" + users.password)) {
          i++;
        }
      }
      if (i === 1) {
        return true;
      } else {
        return false;
      }
    }

    /*
    `save(id, metrics, cb)`
    ------------------------
    Save some metrics with a given id
    Parameters:
    `id`: An integer defining a batch of metrics
    `metrics`: An array of objects with a timestamp and a value
    `callback`: Callback function takes an error or null as parameter
     */

    /*
    save: (id, metrics, callback) ->
      ws = db.createWriteStream()
      ws.on 'error', callback
      ws.on 'close', callback
      for m in metrics
        {timestamp, value} = m
        ws.write key: "metric:#{id}:#{timestamp}", value: value
      ws.end()
     */
  };

}).call(this);
